// Northwind.Client.js
(function(){function executeScript(){
Type.registerNamespace('Northwind.Client');Northwind.Client.EmployeeModule=function(){this.$2=new Northwind.Client.Models.EmployeeService();this.$3=new Northwind.Client.Models.TerritoryService();this.$5();this.$4();}
Northwind.Client.EmployeeModule.prototype={$0:null,$1:null,$2:null,$3:null,get_selectedEmployee:function(){return this.$1;},set_selectedEmployee:function(value){this.$1=value;return value;},get_employeeViewModel:function(){return this.$0;},set_employeeViewModel:function(value){this.$0=value;this.$3.setViewModel(value);this.$B();return value;},$4:function(){$('#create-employee').live('click',ss.Delegate.create(this,this.$6));$('#employee-save').live('click',ss.Delegate.create(this,this.$6));$('#edit').live('click',ss.Delegate.create(this,this.$7));$('#delete').live('click',ss.Delegate.create(this,this.$8));$('#details').live('click',ss.Delegate.create(this,this.$9));$('#TerritoriesAutoSuggest').live('keyup',ss.Delegate.create(this.$3,this.$3.territorySuggestions));$(document).click(ss.Delegate.create(this,function($p1_0){
$('#suggestions').hide();}));},$5:function(){$('#loading').show();$.getJSON('EmployeeRia/GetEmployeeFormViewModel',ss.Delegate.create(this,function($p1_0){
this.set_employeeViewModel($p1_0);}));},$6:function($p0){$p0.preventDefault();if($p0.currentTarget.id==='create-employee'){var $0=new Northwind.Client.Models.Employee();this.$2.displayForm($0);return;}$('.error-message').remove();$('#employee-save').attr('disabled','true');$.post('EmployeeRia/Edit',$('#employee-form-create').serialize(),ss.Delegate.create(this,function($p1_0){
var $1_0=$p1_0;if($1_0.Valid){$('#main').empty();$('#employee-form').remove();this.$5();return;}this.$2.showValidationResults($1_0);}));},$7:function($p0){this.$A($p0.currentTarget.getAttribute('employeeId').toString());this.$2.displayForm(this.get_selectedEmployee());},$8:function($p0){this.$A($p0.currentTarget.getAttribute('employeeId').toString());$.post('EmployeeRia/Delete/'+this.get_selectedEmployee().Id,ss.Delegate.create(this,function($p1_0){
this.get_employeeViewModel().Employees=$p1_0;this.$B();}));},$9:function($p0){this.$A($p0.currentTarget.getAttribute('employeeId').toString());var $0=$.tmpl($('#employee-detail-tmpl').html(),this.get_selectedEmployee());$('#main').append($0);$('#employee-detail').dialog({minWidth:500,close: function(event, ui){$(this).dialog('destroy').remove();}});},$A:function($p0){var $enum1=ss.IEnumerator.getEnumerator(this.$0.Employees);while($enum1.moveNext()){var $0=$enum1.get_current();if($0.Id.toString()===$p0){$0.TerritoriesString=this.$3.territoriestoCSV($0.Territories);this.set_selectedEmployee($0);break;}}},$B:function(){if((this.get_employeeViewModel().Employees.length===0&this.get_employeeViewModel().AvailableTerritories.length===0)===1){return;}$('#main').empty();this.$C();$('#loading').hide();},$C:function(){var $0=new Boolean();$('#main').empty();var $1=$.tmpl($('#employees-table-tmpl').html(),$0);$('#main').append($1);var $enum1=ss.IEnumerator.getEnumerator(this.get_employeeViewModel().Employees);while($enum1.moveNext()){var $2=$enum1.get_current();var $3=$.tmpl($('#employees-table-row-tmpl').html(),$2);$('#employees-table tbody').append($3);}}}
Northwind.Client.EmployeeRia=function(){}
Northwind.Client.EmployeeRia.main=function(){var $0=new Northwind.Client.EmployeeModule();}
Type.registerNamespace('Northwind.Client.Models');Northwind.Client.Models.IEmployeeService=function(){};Northwind.Client.Models.IEmployeeService.registerInterface('Northwind.Client.Models.IEmployeeService');Northwind.Client.Models.ITerritoryService=function(){};Northwind.Client.Models.ITerritoryService.registerInterface('Northwind.Client.Models.ITerritoryService');Northwind.Client.Models.Employee=function(){Northwind.Client.Models.Employee.initializeBase(this);this.Id=0;}
Northwind.Client.Models.Employee.prototype={FirstName:null,FullName:null,LastName:null,PhoneExtension:0,Territories:null,TerritoriesString:null,getEnumerator:function(){return (Type.safeCast(this.Territories,ss.IEnumerable)).getEnumerator();}}
Northwind.Client.Models.EmployeeService=function(){}
Northwind.Client.Models.EmployeeService.prototype={displayForm:function(employee){var $0=$.tmpl($('#employee-form-tmpl').html(),employee);$('#main').append($0);$('#employee-form').dialog({minWidth:500,close: function(event, ui){$(this).dialog('destroy').remove();}});},showValidationResults:function(employee){var $enum1=ss.IEnumerator.getEnumerator(employee.ValidationResultsJson);while($enum1.moveNext()){var $0=$enum1.get_current();if($0.PropertyName==='FirstName'){$('#FirstName').append('<div class=\"error-message\">'+$0.Message+'</div>');}if($0.PropertyName==='LastName'){$('#LastName').append('<div class=\"error-message\">'+$0.Message+'</div>');}if($0.PropertyName==='PhoneExtension'){$('#PhoneExtension').append('<div class=\"error-message\">'+$0.Message+'</div>');}}$('#employee-save').attr('disabled',String.Empty);}}
Northwind.Client.Models.EmployeeViewModel=function(){}
Northwind.Client.Models.EmployeeViewModel.prototype={Employees:null,AvailableTerritories:null}
Northwind.Client.Models.Territory=function(){Northwind.Client.Models.Territory.initializeBase(this);}
Northwind.Client.Models.Territory.prototype={Description:null,RegionBelongingTo:null}
Northwind.Client.Models.TerritoryService=function(){this.$0();}
Northwind.Client.Models.TerritoryService.prototype={employeeViewModel:null,$0:function(){$('#TerritoriesAutoSuggest').live('keyup',ss.Delegate.create(this,this.territorySuggestions));$(document).click(ss.Delegate.create(this,function($p1_0){
if($p1_0.currentTarget.id!=='suggestions'){$('#suggestions').children().remove();}}));$('.child-suggestion').live('click',ss.Delegate.create(this,this.addTerritoryToInput));},setViewModel:function(viewModel){this.employeeViewModel=viewModel;},territorySuggestions:function(eventHandler){eventHandler.preventDefault();$('#suggestions').empty();$('#suggestions').show();var $0=eventHandler.currentTarget;var $1=$0.value.split(',');var $2=0;for(var $3=0;$3<this.employeeViewModel.AvailableTerritories.length;$3++){if($2>2){break;}var $4=this.employeeViewModel.AvailableTerritories[$3];var $5=new RegExp($1[$1.length-1].trim(),'i');if($4.Description.search($5)!==-1){$('#suggestions').append($('<div style=\"margin-left:7px;\" class=\"child-suggestion\">'+$4.Description+'</div>'));$2=$2+1;}}},territoriestoCSV:function(territories){var $0=new String();for(var $1=0;$1<territories.length;$1++){var $2=territories[$1];if($1===territories.length-1){$0=$0+$2.Description.trim();}else{$0=$0+$2.Description.trim()+', ';}}return $0;},addTerritoryToInput:function(eventHandler){var $0=$('#TerritoriesAutoSuggest');var $1=$0.val().split(',');$1[$1.length-1]=' '+eventHandler.currentTarget.innerHTML.trim()+', ';$('#TerritoriesAutoSuggest').val($1.toString());}}
Northwind.Client.EmployeeModule.registerClass('Northwind.Client.EmployeeModule');Northwind.Client.EmployeeRia.registerClass('Northwind.Client.EmployeeRia');Northwind.Client.Models.Employee.registerClass('Northwind.Client.Models.Employee',Object);Northwind.Client.Models.EmployeeService.registerClass('Northwind.Client.Models.EmployeeService',null,Northwind.Client.Models.IEmployeeService);Northwind.Client.Models.EmployeeViewModel.registerClass('Northwind.Client.Models.EmployeeViewModel');Northwind.Client.Models.Territory.registerClass('Northwind.Client.Models.Territory',Object);Northwind.Client.Models.TerritoryService.registerClass('Northwind.Client.Models.TerritoryService',null,Northwind.Client.Models.ITerritoryService);}
ss.loader.registerScript('Northwind.Client',[],executeScript);})();